%% F

function F=ff_func(X)

global L_hw L_ht L_hs L_rw L_rt L_rs L_rtw L_rts
global l_w l_t l_s q_s q_rh q_rk q_hh q_hk
global m_hw m_ht m_hs m_rw m_rt m_rs
global G_hw G_ht G_hs G_rw G_rt G_rs
global K_w K_t K_s K_tw K_tt K_ts g
global l_w_0 l_t_0 l_s_0

q_w=X(1); q_t=X(2);

f1 = conj(K_tw)*conj(q_w) + conj(g)*conj(m_rs)*(conj(G_rs)*((cos(conj(q_w))*conj(L_rw)*sin((5*pi)/2 - conj(q_hh)))/sin(conj(q_hh)) - (cos(conj(q_w))*sin((3*pi)/2 - conj(q_hh) + conj(q_hk))*conj(L_rw)*cos(conj(q_hk) - conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs))))/(sin(conj(q_hh))*conj((1 - (L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))^2/L_rs^2)^(1/2)))) + (cos(conj(q_w))*conj(L_rw)*sin((5*pi)/2 - conj(q_hh)))/sin(conj(q_hh))) + conj(G_rw)*conj(g)*conj(m_rw)*(cos((3*pi)/2 + conj(q_w))*conj(L_rw) + (2*cos(conj(q_hh) + conj(q_w))*conj(L_rw))/sin(conj(q_hh))) - (cos(conj(q_w))*conj(K_t)*conj(L_rw)*(conj(l_t_0) - (sin(conj(q_w))*conj(L_rw) + sin(conj(q_hh) + conj(q_t))*conj(L_rtw))/sin(conj(q_hh))))/sin(conj(q_hh)) + (cos(conj(q_hh) + conj(q_w))*conj(K_w)*conj(L_rw)*(conj(l_w_0) + (sin(conj(q_t))*conj(L_rtw) - sin(conj(q_hh))*conj(L_hw) + sin(conj(q_hh) + conj(q_w))*conj(L_rw))/sin(conj(q_hh))))/sin(conj(q_hh)) + (cos(conj(q_w))*conj(G_ht)*conj(L_rw)*sin((5*pi)/2 - conj(q_hh))*conj(g)*conj(m_ht))/sin(conj(q_hh)) + (2*cos(conj(q_w))*conj(G_rt)*conj(L_rw)*sin((5*pi)/2 - conj(q_hh))*conj(g)*conj(m_rt))/sin(conj(q_hh)) - (cos(conj(q_w))*conj(K_s)*conj(L_rw)*cos(conj(q_hk) - conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs)))*(conj(l_s_0) + (sin(conj(q_hk) - conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs)))*conj(L_rs) - sin(conj(q_hk))*conj(L_hs) + sin(conj(q_t))*conj(L_rts))/sin(conj(q_hk))))/(sin(conj(q_hh))*conj((1 - (L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))^2/L_rs^2)^(1/2))) + (cos(conj(q_w))*sin(conj(q_hk))*conj(K_ts)*conj(L_rw)*conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs)))/(sin(conj(q_hh))*conj(L_rs)*conj((1 - (L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))^2/L_rs^2)^(1/2)));

f2 = conj(K_tt)*conj(q_t) + conj(g)*conj(m_rs)*(conj(G_rs)*((sin((3*pi)/2 - conj(q_hh) + conj(q_hk))*(cos(conj(q_t))*conj(L_rts) - (cos(conj(q_hk) - conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs)))*(cos(conj(q_hk) + conj(q_t))*conj(L_rts) + (sin(conj(q_hk))*cos(conj(q_hh) + conj(q_t))*conj(L_rtw))/sin(conj(q_hh))))/conj((1 - (L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))^2/L_rs^2)^(1/2))))/sin(conj(q_hk)) - cos(conj(q_hh) - (5*pi)/2 + conj(q_t))*conj(L_rts) + (cos(conj(q_hh) + conj(q_t))*conj(L_rtw)*sin((5*pi)/2 - conj(q_hh)))/sin(conj(q_hh))) - cos(conj(q_hh) - (5*pi)/2 + conj(q_t))*conj(L_rts) + (cos(conj(q_hh) + conj(q_t))*conj(L_rtw)*sin((5*pi)/2 - conj(q_hh)))/sin(conj(q_hh))) - conj(G_rt)*conj(g)*conj(m_rt)*(cos(conj(q_hh) - (5*pi)/2 + conj(q_t))*conj(L_rts) + cos(conj(q_hh) - (3*pi)/2 + conj(q_t))*conj(L_rtw) - (2*cos(conj(q_hh) + conj(q_t))*conj(L_rtw)*sin((5*pi)/2 - conj(q_hh)))/sin(conj(q_hh))) + (conj(K_s)*(conj(l_s_0) + (sin(conj(q_hk) - conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs)))*conj(L_rs) - sin(conj(q_hk))*conj(L_hs) + sin(conj(q_t))*conj(L_rts))/sin(conj(q_hk)))*(cos(conj(q_t))*conj(L_rts) - (cos(conj(q_hk) - conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs)))*(cos(conj(q_hk) + conj(q_t))*conj(L_rts) + (sin(conj(q_hk))*cos(conj(q_hh) + conj(q_t))*conj(L_rtw))/sin(conj(q_hh))))/conj((1 - (L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))^2/L_rs^2)^(1/2))))/sin(conj(q_hk)) - (cos(conj(q_hh) + conj(q_t))*conj(K_t)*conj(L_rtw)*(conj(l_t_0) - (sin(conj(q_w))*conj(L_rw) + sin(conj(q_hh) + conj(q_t))*conj(L_rtw))/sin(conj(q_hh))))/sin(conj(q_hh)) + (cos(conj(q_t))*conj(K_w)*conj(L_rtw)*(conj(l_w_0) + (sin(conj(q_t))*conj(L_rtw) - sin(conj(q_hh))*conj(L_hw) + sin(conj(q_hh) + conj(q_w))*conj(L_rw))/sin(conj(q_hh))))/sin(conj(q_hh)) + (conj(K_ts)*conj(asin((L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))/L_rs))*(cos(conj(q_hk) + conj(q_t))*conj(L_rts) + (sin(conj(q_hk))*cos(conj(q_hh) + conj(q_t))*conj(L_rtw))/sin(conj(q_hh))))/(conj(L_rs)*conj((1 - (L_rts*sin(q_hk + q_t) - L_ht*sin(q_hk) + (sin(q_hk)*(L_rtw*sin(q_hh + q_t) + L_rw*sin(q_w)))/sin(q_hh))^2/L_rs^2)^(1/2))) + (2*cos(conj(q_t))*conj(G_rw)*conj(L_rtw)*conj(g)*conj(m_rw))/sin(conj(q_hh)) + (cos(conj(q_hh) + conj(q_t))*conj(G_ht)*conj(L_rtw)*sin((5*pi)/2 - conj(q_hh))*conj(g)*conj(m_ht))/sin(conj(q_hh));

F = [f1 f2]';    